using Azure;
using Azure.Data.Tables;

namespace SamlCertRotation.Models;

/// <summary>
/// Policy configuration for certificate rotation
/// </summary>
public class RotationPolicy : ITableEntity
{
    /// <summary>
    /// Partition key - typically "Policy" for global or AppId for app-specific
    /// </summary>
    public string PartitionKey { get; set; } = "GlobalPolicy";

    /// <summary>
    /// Row key - "Default" for global policy or specific policy name
    /// </summary>
    public string RowKey { get; set; } = "Default";

    /// <summary>
    /// Days before expiry to create a new certificate
    /// </summary>
    public int CreateCertDaysBeforeExpiry { get; set; } = 60;

    /// <summary>
    /// Days before expiry to activate the new certificate
    /// </summary>
    public int ActivateCertDaysBeforeExpiry { get; set; } = 30;

    /// <summary>
    /// Lifespan in days for newly created certificates (1-1095, default 1095 = ~3 years)
    /// </summary>
    public int NewCertLifespanDays { get; set; } = 1095;

    /// <summary>
    /// Whether the policy is enabled
    /// </summary>
    public bool IsEnabled { get; set; } = true;

    /// <summary>
    /// Description for this policy
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Last modified timestamp
    /// </summary>
    public DateTimeOffset? Timestamp { get; set; }

    /// <summary>
    /// ETag for optimistic concurrency
    /// </summary>
    public ETag ETag { get; set; }
}

/// <summary>
/// App-specific policy override
/// </summary>
public class AppPolicy : ITableEntity
{
    /// <summary>
    /// Partition key - "AppPolicy"
    /// </summary>
    public string PartitionKey { get; set; } = "AppPolicy";

    /// <summary>
    /// Row key - The service principal object ID
    /// </summary>
    public string RowKey { get; set; } = string.Empty;

    /// <summary>
    /// Application display name (for reference)
    /// </summary>
    public string? AppDisplayName { get; set; }

    /// <summary>
    /// Override: Days before expiry to create a new certificate (null = use global)
    /// </summary>
    public int? CreateCertDaysBeforeExpiry { get; set; }

    /// <summary>
    /// Override: Days before expiry to activate the new certificate (null = use global)
    /// </summary>
    public int? ActivateCertDaysBeforeExpiry { get; set; }

    /// <summary>
    /// Override: create certs for notify-only apps (null = use global, true = enabled, false = disabled)
    /// </summary>
    public bool? CreateCertsForNotifyOverride { get; set; }

    /// <summary>
    /// Override: lifespan in days for newly created certificates (null = use global, 1-1095)
    /// </summary>
    public int? NewCertLifespanDays { get; set; }

    /// <summary>
    /// Additional notification emails specific to this app
    /// </summary>
    public string? AdditionalNotificationEmails { get; set; }

    // ── Certificate source ────────────────────────────────────────────────────

    /// <summary>
    /// Overrides the global certificate source type for this app.
    /// <list type="bullet">
    ///   <item><term>EntraID</term><description>Certificate is generated and managed by Entra ID (default). Private key is not accessible.</description></item>
    ///   <item><term>OrgPKI</term><description>Certificate is generated by org PKI and uploaded to Entra ID. Private key is stored in Key Vault and accessible for SAML assertion generation.</description></item>
    /// </list>
    /// Null means inherit from the global setting <c>DefaultCertSourceType</c>.
    /// </summary>
    public string? CertSourceTypeOverride { get; set; }

    /// <summary>
    /// URI of the Key Vault that holds this app's Org PKI private key.
    /// Only relevant when the effective <c>CertSourceType</c> is <c>OrgPKI</c>
    /// and the auth type is <c>OAuthSamlAssertionGrant</c>.
    /// If null, the global <c>KeyVaultUri</c> app setting is used.
    /// </summary>
    public string? OrgPkiKeyVaultUri { get; set; }

    /// <summary>
    /// Last modified timestamp
    /// </summary>
    public DateTimeOffset? Timestamp { get; set; }

    /// <summary>
    /// ETag for optimistic concurrency
    /// </summary>
    public ETag ETag { get; set; }
}
